# =========================
# CONFIG SMARTLINK NOTIFICACIONES
# =========================

api:
  base_url: "http://localhost:8000"
  latencia:
    get_latencia_stats: "/latencia/get_latencia_stats"
    get_latencia_stats_summary: "/latencia/get_latencia_stats_summary"

general:
  timezone: "America/Santiago"
  default_hours_back: 8
  max_message_length: 3500

whatsapp:
  # Grupos de destinatarios mudslice
  mudslice_groups:
    collahuasi:
      - "+56977566595"
      - "120363027104819888@g.us"
      - "+56971083001"
      - "+56982280571"
      - "+56976426949"
      - "+56939496396"
    test:
      - "+56977566595"
    emergencia:
      - "120363027104819888@g.us"
      - "+56977566595"
    #default:
    #  - "+56977566595"

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  remitente: "ccarmona@hcglsa.com"
  smtp_password: "rxnvhmpucetngmcj"   # ⚠️ ideal moverlo a variable de entorno EMAIL_PASSWORD
  destinatarios:
    - "rxvega@collahuasi.cl"
    - "heveliz@collahuasi.cl"
    - "ginunez@collahuasi.cl"
    - "darivera@collahuasi.cl"
    - "teamautomatizacionmina@collahuasi.cl"
  cc:
    - "ccastillo@hcglsa.com"
    - "ccarmona@hcglsa.com"
    - "support@hcglsa.com"

empresas:
  collahuasi:
    nombre_corto: "Collahuasi"
  default:
    nombre_corto: "Cliente"

mensajes:
  email_subject: "Reporte de latencia - {empresa} - últimas {horas}h"
  whatsapp_intro: "📊 Reporte Smartlink - {empresa}"
