# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Alert.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Alert.proto',
  package='rajant.bc.proto',
  syntax='proto2',
  serialized_options=_b('\n\021com.rajant.alertsB\017AlertMetaProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x0b\x41lert.proto\x12\x0frajant.bc.proto\x1a\x0c\x43ommon.proto\"6\n\x08\x41lertSet\x12*\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x1b.rajant.bc.proto.AlertEntry\"\xd1\x01\n\nAlertEntry\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12(\n\x04meta\x18\x02 \x01(\x0b\x32\x1a.rajant.bc.proto.AlertMeta\x12\x36\n\x08override\x18\x03 \x03(\x0b\x32$.rajant.bc.proto.AlertEntry.Override\x12\x0f\n\x07\x65numTxt\x18\x04 \x01(\t\x1a\x42\n\x08Override\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12(\n\x04meta\x18\x02 \x01(\x0b\x32\x1a.rajant.bc.proto.AlertMeta\"\x90\x01\n\tAlertMeta\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x10.Alert.AlertType:\x0bINFORMATION\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12\x61pplicationMessage\x18\x03 \x01(\t\x12\x11\n\x03led\x18\x04 \x01(\x08:\x04true\x12\x16\n\x07\x66\x61\x63tory\x18\x05 \x01(\x08:\x05\x66\x61lseB1\n\x11\x63om.rajant.alertsB\x0f\x41lertMetaProtosH\x02Z\t.;bcproto')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_ALERTSET = _descriptor.Descriptor(
  name='AlertSet',
  full_name='rajant.bc.proto.AlertSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='rajant.bc.proto.AlertSet.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=100,
)


_ALERTENTRY_OVERRIDE = _descriptor.Descriptor(
  name='Override',
  full_name='rajant.bc.proto.AlertEntry.Override',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='rajant.bc.proto.AlertEntry.Override.mode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='rajant.bc.proto.AlertEntry.Override.meta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=312,
)

_ALERTENTRY = _descriptor.Descriptor(
  name='AlertEntry',
  full_name='rajant.bc.proto.AlertEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='rajant.bc.proto.AlertEntry.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='rajant.bc.proto.AlertEntry.meta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='override', full_name='rajant.bc.proto.AlertEntry.override', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enumTxt', full_name='rajant.bc.proto.AlertEntry.enumTxt', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ALERTENTRY_OVERRIDE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=312,
)


_ALERTMETA = _descriptor.Descriptor(
  name='AlertMeta',
  full_name='rajant.bc.proto.AlertMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rajant.bc.proto.AlertMeta.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='rajant.bc.proto.AlertMeta.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='applicationMessage', full_name='rajant.bc.proto.AlertMeta.applicationMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='led', full_name='rajant.bc.proto.AlertMeta.led', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='factory', full_name='rajant.bc.proto.AlertMeta.factory', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=459,
)

_ALERTSET.fields_by_name['entry'].message_type = _ALERTENTRY
_ALERTENTRY_OVERRIDE.fields_by_name['meta'].message_type = _ALERTMETA
_ALERTENTRY_OVERRIDE.containing_type = _ALERTENTRY
_ALERTENTRY.fields_by_name['meta'].message_type = _ALERTMETA
_ALERTENTRY.fields_by_name['override'].message_type = _ALERTENTRY_OVERRIDE
_ALERTMETA.fields_by_name['type'].enum_type = Common__pb2._ALERT_ALERTTYPE
DESCRIPTOR.message_types_by_name['AlertSet'] = _ALERTSET
DESCRIPTOR.message_types_by_name['AlertEntry'] = _ALERTENTRY
DESCRIPTOR.message_types_by_name['AlertMeta'] = _ALERTMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlertSet = _reflection.GeneratedProtocolMessageType('AlertSet', (_message.Message,), dict(
  DESCRIPTOR = _ALERTSET,
  __module__ = 'Alert_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.AlertSet)
  ))
_sym_db.RegisterMessage(AlertSet)

AlertEntry = _reflection.GeneratedProtocolMessageType('AlertEntry', (_message.Message,), dict(

  Override = _reflection.GeneratedProtocolMessageType('Override', (_message.Message,), dict(
    DESCRIPTOR = _ALERTENTRY_OVERRIDE,
    __module__ = 'Alert_pb2'
    # @@protoc_insertion_point(class_scope:rajant.bc.proto.AlertEntry.Override)
    ))
  ,
  DESCRIPTOR = _ALERTENTRY,
  __module__ = 'Alert_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.AlertEntry)
  ))
_sym_db.RegisterMessage(AlertEntry)
_sym_db.RegisterMessage(AlertEntry.Override)

AlertMeta = _reflection.GeneratedProtocolMessageType('AlertMeta', (_message.Message,), dict(
  DESCRIPTOR = _ALERTMETA,
  __module__ = 'Alert_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.AlertMeta)
  ))
_sym_db.RegisterMessage(AlertMeta)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
