# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Backup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ModelDatabase_pb2 as ModelDatabase__pb2
from . import Rule_pb2 as Rule__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Backup.proto',
  package='rajant.bc.proto',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\014BackupProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x0c\x42\x61\x63kup.proto\x12\x0frajant.bc.proto\x1a\x13ModelDatabase.proto\x1a\nRule.proto\"\xa9\x01\n\x06\x42\x61\x63kup\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12#\n\x08platform\x18\x02 \x01(\x0e\x32\x11.BcModel.Platform\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\r\n\x05\x62uild\x18\x04 \x01(\t\x12\r\n\x05model\x18\x07 \x01(\t\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x0f\n\x07\x63omment\x18\t \x01(\t\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\"|\n\rBackupRequest\x12\'\n\x06\x62\x61\x63kup\x18\x01 \x01(\x0b\x32\x17.rajant.bc.proto.Backup\x12\x12\n\npassphrase\x18\x02 \x01(\t\x12.\n\x05scope\x18\x03 \x01(\x0e\x32\x1f.rajant.bc.proto.Rule.SyncScopeB4\n\x17\x63om.rajant.bcapi.protosB\x0c\x42\x61\x63kupProtosH\x02Z\t.;bcproto')
  ,
  dependencies=[ModelDatabase__pb2.DESCRIPTOR,Rule__pb2.DESCRIPTOR,])




_BACKUP = _descriptor.Descriptor(
  name='Backup',
  full_name='rajant.bc.proto.Backup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial', full_name='rajant.bc.proto.Backup.serial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='rajant.bc.proto.Backup.platform', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='rajant.bc.proto.Backup.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build', full_name='rajant.bc.proto.Backup.build', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='rajant.bc.proto.Backup.model', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='rajant.bc.proto.Backup.name', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='rajant.bc.proto.Backup.comment', index=6,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='rajant.bc.proto.Backup.format', index=7,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='rajant.bc.proto.Backup.data', index=8,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=236,
)


_BACKUPREQUEST = _descriptor.Descriptor(
  name='BackupRequest',
  full_name='rajant.bc.proto.BackupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backup', full_name='rajant.bc.proto.BackupRequest.backup', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passphrase', full_name='rajant.bc.proto.BackupRequest.passphrase', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='rajant.bc.proto.BackupRequest.scope', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=362,
)

_BACKUP.fields_by_name['platform'].enum_type = ModelDatabase__pb2._BCMODEL_PLATFORM
_BACKUPREQUEST.fields_by_name['backup'].message_type = _BACKUP
_BACKUPREQUEST.fields_by_name['scope'].enum_type = Rule__pb2._RULE_SYNCSCOPE
DESCRIPTOR.message_types_by_name['Backup'] = _BACKUP
DESCRIPTOR.message_types_by_name['BackupRequest'] = _BACKUPREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Backup = _reflection.GeneratedProtocolMessageType('Backup', (_message.Message,), dict(
  DESCRIPTOR = _BACKUP,
  __module__ = 'Backup_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.Backup)
  ))
_sym_db.RegisterMessage(Backup)

BackupRequest = _reflection.GeneratedProtocolMessageType('BackupRequest', (_message.Message,), dict(
  DESCRIPTOR = _BACKUPREQUEST,
  __module__ = 'Backup_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.BackupRequest)
  ))
_sym_db.RegisterMessage(BackupRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
