# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigMeta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConfigMeta.proto',
  package='rajant.bc.proto',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\020ConfigMetaProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x10\x43onfigMeta.proto\x12\x0frajant.bc.proto\"Y\n\nConfigMeta\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0c\n\x04help\x18\x03 \x01(\t\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x10\n\x08\x65numText\x18\x05 \x03(\t\"A\n\rConfigMetaSet\x12\x30\n\x0b\x63onfigMetas\x18\x01 \x03(\x0b\x32\x1b.rajant.bc.proto.ConfigMetaB8\n\x17\x63om.rajant.bcapi.protosB\x10\x43onfigMetaProtosH\x02Z\t.;bcproto')
)




_CONFIGMETA = _descriptor.Descriptor(
  name='ConfigMeta',
  full_name='rajant.bc.proto.ConfigMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='rajant.bc.proto.ConfigMeta.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='rajant.bc.proto.ConfigMeta.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='help', full_name='rajant.bc.proto.ConfigMeta.help', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='rajant.bc.proto.ConfigMeta.comment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enumText', full_name='rajant.bc.proto.ConfigMeta.enumText', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=126,
)


_CONFIGMETASET = _descriptor.Descriptor(
  name='ConfigMetaSet',
  full_name='rajant.bc.proto.ConfigMetaSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configMetas', full_name='rajant.bc.proto.ConfigMetaSet.configMetas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=193,
)

_CONFIGMETASET.fields_by_name['configMetas'].message_type = _CONFIGMETA
DESCRIPTOR.message_types_by_name['ConfigMeta'] = _CONFIGMETA
DESCRIPTOR.message_types_by_name['ConfigMetaSet'] = _CONFIGMETASET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigMeta = _reflection.GeneratedProtocolMessageType('ConfigMeta', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGMETA,
  __module__ = 'ConfigMeta_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.ConfigMeta)
  ))
_sym_db.RegisterMessage(ConfigMeta)

ConfigMetaSet = _reflection.GeneratedProtocolMessageType('ConfigMetaSet', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGMETASET,
  __module__ = 'ConfigMeta_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.ConfigMetaSet)
  ))
_sym_db.RegisterMessage(ConfigMetaSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
