# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileTransfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FileTransfer.proto',
  package='rajant.bc.proto',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\022FileTransferProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x12\x46ileTransfer.proto\x12\x0frajant.bc.proto\"\xd2\x01\n\x0c\x46ileTransfer\x12\x32\n\x05start\x18\x01 \x01(\x0b\x32#.rajant.bc.proto.FileTransfer.Start\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06\x63\x61ncel\x18\x03 \x01(\x08\x12\x10\n\x08\x63lientId\x18\x04 \x01(\t\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x1aP\n\x05Start\x12\x0e\n\x06\x61ppend\x18\x01 \x01(\x08\x12\x14\n\x0c\x65xpectedSize\x18\x02 \x02(\r\x12\x0f\n\x07version\x18\x03 \x02(\t\x12\x10\n\x08\x66ilename\x18\x04 \x01(\tB:\n\x17\x63om.rajant.bcapi.protosB\x12\x46ileTransferProtosH\x02Z\t.;bcproto')
)




_FILETRANSFER_START = _descriptor.Descriptor(
  name='Start',
  full_name='rajant.bc.proto.FileTransfer.Start',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='append', full_name='rajant.bc.proto.FileTransfer.Start.append', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expectedSize', full_name='rajant.bc.proto.FileTransfer.Start.expectedSize', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='rajant.bc.proto.FileTransfer.Start.version', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='rajant.bc.proto.FileTransfer.Start.filename', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=250,
)

_FILETRANSFER = _descriptor.Descriptor(
  name='FileTransfer',
  full_name='rajant.bc.proto.FileTransfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='rajant.bc.proto.FileTransfer.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='rajant.bc.proto.FileTransfer.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancel', full_name='rajant.bc.proto.FileTransfer.cancel', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientId', full_name='rajant.bc.proto.FileTransfer.clientId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='rajant.bc.proto.FileTransfer.done', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FILETRANSFER_START, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=250,
)

_FILETRANSFER_START.containing_type = _FILETRANSFER
_FILETRANSFER.fields_by_name['start'].message_type = _FILETRANSFER_START
DESCRIPTOR.message_types_by_name['FileTransfer'] = _FILETRANSFER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileTransfer = _reflection.GeneratedProtocolMessageType('FileTransfer', (_message.Message,), dict(

  Start = _reflection.GeneratedProtocolMessageType('Start', (_message.Message,), dict(
    DESCRIPTOR = _FILETRANSFER_START,
    __module__ = 'FileTransfer_pb2'
    # @@protoc_insertion_point(class_scope:rajant.bc.proto.FileTransfer.Start)
    ))
  ,
  DESCRIPTOR = _FILETRANSFER,
  __module__ = 'FileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.FileTransfer)
  ))
_sym_db.RegisterMessage(FileTransfer)
_sym_db.RegisterMessage(FileTransfer.Start)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
