# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Gps.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\tGpsProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\tGps.proto\"\xde\x04\n\x03GPS\x12(\n\tgpsSwitch\x18\x01 \x01(\x0b\x32\x15.GPS.GPSEnabledSwitch\x12&\n\x06gpsPos\x18\x02 \x01(\x0b\x32\x16.GPS.GPSPositionReport\x12&\n\x06gpsVel\x18\x03 \x01(\x0b\x32\x16.GPS.GPSVelocityReport\x12*\n\x06gpsRMC\x18\x04 \x01(\x0b\x32\x1a.GPS.GPSRecommendedMinimum\x1a#\n\x10GPSEnabledSwitch\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x1a\xae\x01\n\x11GPSPositionReport\x12\x0f\n\x07gpsTime\x18\x01 \x01(\x02\x12\x0e\n\x06gpsLat\x18\x02 \x01(\t\x12\x0f\n\x07gpsLong\x18\x03 \x01(\t\x12\x15\n\rgpsPrecisionH\x18\x04 \x01(\x02\x12\x12\n\ngpsQuality\x18\x05 \x01(\x02\x12\x15\n\rgpsSatsInView\x18\x06 \x01(\r\x12\x0e\n\x06gpsAlt\x18\x07 \x01(\x02\x12\x15\n\rgpsGeoidalSep\x18\x08 \x01(\x02\x1ax\n\x11GPSVelocityReport\x12\x1b\n\x13gpsTrackDegreesTrue\x18\x01 \x01(\x02\x12\x1a\n\x12gpsTrackDegreesMag\x18\x02 \x01(\x02\x12\x15\n\rgpsSpeedKnots\x18\x03 \x01(\x02\x12\x13\n\x0bgpsSpeedKph\x18\x04 \x01(\x02\x1a\x61\n\x15GPSRecommendedMinimum\x12\x0f\n\x07gpsTime\x18\x01 \x01(\x02\x12\x11\n\tgpsStatus\x18\x02 \x01(\x08\x12\x0f\n\x07gpsDate\x18\x03 \x01(\x02\x12\x13\n\x0bgpsDateTime\x18\x04 \x01(\tB1\n\x17\x63om.rajant.bcapi.protosB\tGpsProtosH\x02Z\t.;bcproto')
)




_GPS_GPSENABLEDSWITCH = _descriptor.Descriptor(
  name='GPSEnabledSwitch',
  full_name='GPS.GPSEnabledSwitch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='GPS.GPSEnabledSwitch.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=222,
)

_GPS_GPSPOSITIONREPORT = _descriptor.Descriptor(
  name='GPSPositionReport',
  full_name='GPS.GPSPositionReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpsTime', full_name='GPS.GPSPositionReport.gpsTime', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsLat', full_name='GPS.GPSPositionReport.gpsLat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsLong', full_name='GPS.GPSPositionReport.gpsLong', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsPrecisionH', full_name='GPS.GPSPositionReport.gpsPrecisionH', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsQuality', full_name='GPS.GPSPositionReport.gpsQuality', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsSatsInView', full_name='GPS.GPSPositionReport.gpsSatsInView', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsAlt', full_name='GPS.GPSPositionReport.gpsAlt', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsGeoidalSep', full_name='GPS.GPSPositionReport.gpsGeoidalSep', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=399,
)

_GPS_GPSVELOCITYREPORT = _descriptor.Descriptor(
  name='GPSVelocityReport',
  full_name='GPS.GPSVelocityReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpsTrackDegreesTrue', full_name='GPS.GPSVelocityReport.gpsTrackDegreesTrue', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsTrackDegreesMag', full_name='GPS.GPSVelocityReport.gpsTrackDegreesMag', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsSpeedKnots', full_name='GPS.GPSVelocityReport.gpsSpeedKnots', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsSpeedKph', full_name='GPS.GPSVelocityReport.gpsSpeedKph', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=521,
)

_GPS_GPSRECOMMENDEDMINIMUM = _descriptor.Descriptor(
  name='GPSRecommendedMinimum',
  full_name='GPS.GPSRecommendedMinimum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpsTime', full_name='GPS.GPSRecommendedMinimum.gpsTime', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsStatus', full_name='GPS.GPSRecommendedMinimum.gpsStatus', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsDate', full_name='GPS.GPSRecommendedMinimum.gpsDate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsDateTime', full_name='GPS.GPSRecommendedMinimum.gpsDateTime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=620,
)

_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpsSwitch', full_name='GPS.gpsSwitch', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsPos', full_name='GPS.gpsPos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsVel', full_name='GPS.gpsVel', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpsRMC', full_name='GPS.gpsRMC', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GPS_GPSENABLEDSWITCH, _GPS_GPSPOSITIONREPORT, _GPS_GPSVELOCITYREPORT, _GPS_GPSRECOMMENDEDMINIMUM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=620,
)

_GPS_GPSENABLEDSWITCH.containing_type = _GPS
_GPS_GPSPOSITIONREPORT.containing_type = _GPS
_GPS_GPSVELOCITYREPORT.containing_type = _GPS
_GPS_GPSRECOMMENDEDMINIMUM.containing_type = _GPS
_GPS.fields_by_name['gpsSwitch'].message_type = _GPS_GPSENABLEDSWITCH
_GPS.fields_by_name['gpsPos'].message_type = _GPS_GPSPOSITIONREPORT
_GPS.fields_by_name['gpsVel'].message_type = _GPS_GPSVELOCITYREPORT
_GPS.fields_by_name['gpsRMC'].message_type = _GPS_GPSRECOMMENDEDMINIMUM
DESCRIPTOR.message_types_by_name['GPS'] = _GPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPS = _reflection.GeneratedProtocolMessageType('GPS', (_message.Message,), dict(

  GPSEnabledSwitch = _reflection.GeneratedProtocolMessageType('GPSEnabledSwitch', (_message.Message,), dict(
    DESCRIPTOR = _GPS_GPSENABLEDSWITCH,
    __module__ = 'Gps_pb2'
    # @@protoc_insertion_point(class_scope:GPS.GPSEnabledSwitch)
    ))
  ,

  GPSPositionReport = _reflection.GeneratedProtocolMessageType('GPSPositionReport', (_message.Message,), dict(
    DESCRIPTOR = _GPS_GPSPOSITIONREPORT,
    __module__ = 'Gps_pb2'
    # @@protoc_insertion_point(class_scope:GPS.GPSPositionReport)
    ))
  ,

  GPSVelocityReport = _reflection.GeneratedProtocolMessageType('GPSVelocityReport', (_message.Message,), dict(
    DESCRIPTOR = _GPS_GPSVELOCITYREPORT,
    __module__ = 'Gps_pb2'
    # @@protoc_insertion_point(class_scope:GPS.GPSVelocityReport)
    ))
  ,

  GPSRecommendedMinimum = _reflection.GeneratedProtocolMessageType('GPSRecommendedMinimum', (_message.Message,), dict(
    DESCRIPTOR = _GPS_GPSRECOMMENDEDMINIMUM,
    __module__ = 'Gps_pb2'
    # @@protoc_insertion_point(class_scope:GPS.GPSRecommendedMinimum)
    ))
  ,
  DESCRIPTOR = _GPS,
  __module__ = 'Gps_pb2'
  # @@protoc_insertion_point(class_scope:GPS)
  ))
_sym_db.RegisterMessage(GPS)
_sym_db.RegisterMessage(GPS.GPSEnabledSwitch)
_sym_db.RegisterMessage(GPS.GPSPositionReport)
_sym_db.RegisterMessage(GPS.GPSVelocityReport)
_sym_db.RegisterMessage(GPS.GPSRecommendedMinimum)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
