# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Hardware.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Hardware.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\016HardwareProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x0eHardware.proto\x1a\x0c\x43ommon.proto\"\x8c\x05\n\x08Hardware\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x0f\n\x07profile\x18\x02 \x01(\t\x12\r\n\x05imkey\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x12\n\nv10factory\x18\x05 \x01(\x0c\x12\x13\n\x0b\x63ountrycode\x18\x06 \x01(\r\x12,\n\x0corganization\x18\x07 \x01(\x0b\x32\x16.Hardware.Organization\x12\x1c\n\rimbcompatible\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x0f\x61llowDfsControl\x18\n \x01(\x08\x12,\n\x0clinkedDevice\x18\x0b \x03(\x0b\x32\x16.Hardware.LinkedDevice\x12&\n\tboardData\x18\r \x01(\x0b\x32\x13.Hardware.BoardData\x12(\n\ndeployment\x18\x0e \x01(\x0b\x32\x14.Hardware.Deployment\x1a@\n\x0cOrganization\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64ivision\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x1a;\n\x0cLinkedDevice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\n.BCRAction:\x03\x41\x44\x44\x1a;\n\x0b\x41ssignedMac\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12\x1f\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\n.BCRAction:\x03\x41\x44\x44\x1aV\n\tBoardData\x12*\n\x0b\x61ssignedMac\x18\x01 \x03(\x0b\x32\x15.Hardware.AssignedMac\x12\x0e\n\x06serial\x18\x02 \x01(\r\x12\r\n\x05ident\x18\x03 \x01(\t\x1a \n\nDeployment\x12\x12\n\npassphrase\x18\x01 \x01(\tB6\n\x17\x63om.rajant.bcapi.protosB\x0eHardwareProtosH\x02Z\t.;bcproto')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_HARDWARE_ORGANIZATION = _descriptor.Descriptor(
  name='Organization',
  full_name='Hardware.Organization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Hardware.Organization.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='division', full_name='Hardware.Organization.division', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='Hardware.Organization.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=441,
)

_HARDWARE_LINKEDDEVICE = _descriptor.Descriptor(
  name='LinkedDevice',
  full_name='Hardware.LinkedDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Hardware.LinkedDevice.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Hardware.LinkedDevice.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=502,
)

_HARDWARE_ASSIGNEDMAC = _descriptor.Descriptor(
  name='AssignedMac',
  full_name='Hardware.AssignedMac',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='Hardware.AssignedMac.mac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Hardware.AssignedMac.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=563,
)

_HARDWARE_BOARDDATA = _descriptor.Descriptor(
  name='BoardData',
  full_name='Hardware.BoardData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assignedMac', full_name='Hardware.BoardData.assignedMac', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial', full_name='Hardware.BoardData.serial', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ident', full_name='Hardware.BoardData.ident', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=651,
)

_HARDWARE_DEPLOYMENT = _descriptor.Descriptor(
  name='Deployment',
  full_name='Hardware.Deployment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='passphrase', full_name='Hardware.Deployment.passphrase', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=685,
)

_HARDWARE = _descriptor.Descriptor(
  name='Hardware',
  full_name='Hardware',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial', full_name='Hardware.serial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='Hardware.profile', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imkey', full_name='Hardware.imkey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='Hardware.date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v10factory', full_name='Hardware.v10factory', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='countrycode', full_name='Hardware.countrycode', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organization', full_name='Hardware.organization', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imbcompatible', full_name='Hardware.imbcompatible', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allowDfsControl', full_name='Hardware.allowDfsControl', index=8,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkedDevice', full_name='Hardware.linkedDevice', index=9,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boardData', full_name='Hardware.boardData', index=10,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deployment', full_name='Hardware.deployment', index=11,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HARDWARE_ORGANIZATION, _HARDWARE_LINKEDDEVICE, _HARDWARE_ASSIGNEDMAC, _HARDWARE_BOARDDATA, _HARDWARE_DEPLOYMENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=685,
)

_HARDWARE_ORGANIZATION.containing_type = _HARDWARE
_HARDWARE_LINKEDDEVICE.fields_by_name['action'].enum_type = Common__pb2._BCRACTION
_HARDWARE_LINKEDDEVICE.containing_type = _HARDWARE
_HARDWARE_ASSIGNEDMAC.fields_by_name['action'].enum_type = Common__pb2._BCRACTION
_HARDWARE_ASSIGNEDMAC.containing_type = _HARDWARE
_HARDWARE_BOARDDATA.fields_by_name['assignedMac'].message_type = _HARDWARE_ASSIGNEDMAC
_HARDWARE_BOARDDATA.containing_type = _HARDWARE
_HARDWARE_DEPLOYMENT.containing_type = _HARDWARE
_HARDWARE.fields_by_name['organization'].message_type = _HARDWARE_ORGANIZATION
_HARDWARE.fields_by_name['linkedDevice'].message_type = _HARDWARE_LINKEDDEVICE
_HARDWARE.fields_by_name['boardData'].message_type = _HARDWARE_BOARDDATA
_HARDWARE.fields_by_name['deployment'].message_type = _HARDWARE_DEPLOYMENT
DESCRIPTOR.message_types_by_name['Hardware'] = _HARDWARE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hardware = _reflection.GeneratedProtocolMessageType('Hardware', (_message.Message,), dict(

  Organization = _reflection.GeneratedProtocolMessageType('Organization', (_message.Message,), dict(
    DESCRIPTOR = _HARDWARE_ORGANIZATION,
    __module__ = 'Hardware_pb2'
    # @@protoc_insertion_point(class_scope:Hardware.Organization)
    ))
  ,

  LinkedDevice = _reflection.GeneratedProtocolMessageType('LinkedDevice', (_message.Message,), dict(
    DESCRIPTOR = _HARDWARE_LINKEDDEVICE,
    __module__ = 'Hardware_pb2'
    # @@protoc_insertion_point(class_scope:Hardware.LinkedDevice)
    ))
  ,

  AssignedMac = _reflection.GeneratedProtocolMessageType('AssignedMac', (_message.Message,), dict(
    DESCRIPTOR = _HARDWARE_ASSIGNEDMAC,
    __module__ = 'Hardware_pb2'
    # @@protoc_insertion_point(class_scope:Hardware.AssignedMac)
    ))
  ,

  BoardData = _reflection.GeneratedProtocolMessageType('BoardData', (_message.Message,), dict(
    DESCRIPTOR = _HARDWARE_BOARDDATA,
    __module__ = 'Hardware_pb2'
    # @@protoc_insertion_point(class_scope:Hardware.BoardData)
    ))
  ,

  Deployment = _reflection.GeneratedProtocolMessageType('Deployment', (_message.Message,), dict(
    DESCRIPTOR = _HARDWARE_DEPLOYMENT,
    __module__ = 'Hardware_pb2'
    # @@protoc_insertion_point(class_scope:Hardware.Deployment)
    ))
  ,
  DESCRIPTOR = _HARDWARE,
  __module__ = 'Hardware_pb2'
  # @@protoc_insertion_point(class_scope:Hardware)
  ))
_sym_db.RegisterMessage(Hardware)
_sym_db.RegisterMessage(Hardware.Organization)
_sym_db.RegisterMessage(Hardware.LinkedDevice)
_sym_db.RegisterMessage(Hardware.AssignedMac)
_sym_db.RegisterMessage(Hardware.BoardData)
_sym_db.RegisterMessage(Hardware.Deployment)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
