# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ModelDatabase_pb2 as ModelDatabase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Image.proto',
  package='rajant.bc.proto',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\013ImageProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x0bImage.proto\x12\x0frajant.bc.proto\x1a\x13ModelDatabase.proto\"\xd9\x04\n\x18\x42readCrumbImageContainer\x12H\n\x05image\x18\x01 \x03(\x0b\x32\x39.rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage\x1a\x8d\x03\n\x0f\x42readCrumbImage\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66ullpath\x18\x02 \x01(\t\x12\x18\n\x07version\x18\x03 \x01(\t:\x07unknown\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0b\n\x03md5\x18\x05 \x01(\t\x12\x0c\n\x04size\x18\x06 \x01(\x04\x12\x0e\n\x06offset\x18\x07 \x01(\x04\x12\x12\n\nbuild_user\x18\t \x01(\t\x12\x16\n\x0e\x62uild_hostinfo\x18\n \x01(\t\x12\x12\n\nbuild_when\x18\x0b \x01(\t\x12\x14\n\x0c\x62uild_number\x18\x0c \x01(\t\x12I\n\nv10factory\x18\x0e \x03(\x0b\x32\x35.rajant.bc.proto.BreadCrumbImageContainer.FactoryBlob\x12\x19\n\x11\x62uild_description\x18\x0f \x01(\t\x12\x46\n\x07modeldb\x18\x10 \x01(\x0b\x32\x35.rajant.bc.proto.BreadCrumbImageContainer.ModelDbInfo\x1a\x38\n\x0bModelDbInfo\x12\x0e\n\x06offset\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0b\n\x03md5\x18\x03 \x01(\t\x1a)\n\x0b\x46\x61\x63toryBlob\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x62lob\x18\x02 \x01(\x0c\x42\x33\n\x17\x63om.rajant.bcapi.protosB\x0bImageProtosH\x02Z\t.;bcproto')
  ,
  dependencies=[ModelDatabase__pb2.DESCRIPTOR,])




_BREADCRUMBIMAGECONTAINER_BREADCRUMBIMAGE = _descriptor.Descriptor(
  name='BreadCrumbImage',
  full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fullpath', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.fullpath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("unknown").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='md5', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.md5', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.size', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.offset', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_user', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.build_user', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_hostinfo', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.build_hostinfo', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_when', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.build_when', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_number', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.build_number', index=10,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v10factory', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.v10factory', index=11,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_description', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.build_description', index=12,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modeldb', full_name='rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage.modeldb', index=13,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=554,
)

_BREADCRUMBIMAGECONTAINER_MODELDBINFO = _descriptor.Descriptor(
  name='ModelDbInfo',
  full_name='rajant.bc.proto.BreadCrumbImageContainer.ModelDbInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='rajant.bc.proto.BreadCrumbImageContainer.ModelDbInfo.offset', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='rajant.bc.proto.BreadCrumbImageContainer.ModelDbInfo.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='md5', full_name='rajant.bc.proto.BreadCrumbImageContainer.ModelDbInfo.md5', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=612,
)

_BREADCRUMBIMAGECONTAINER_FACTORYBLOB = _descriptor.Descriptor(
  name='FactoryBlob',
  full_name='rajant.bc.proto.BreadCrumbImageContainer.FactoryBlob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rajant.bc.proto.BreadCrumbImageContainer.FactoryBlob.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blob', full_name='rajant.bc.proto.BreadCrumbImageContainer.FactoryBlob.blob', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=655,
)

_BREADCRUMBIMAGECONTAINER = _descriptor.Descriptor(
  name='BreadCrumbImageContainer',
  full_name='rajant.bc.proto.BreadCrumbImageContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='rajant.bc.proto.BreadCrumbImageContainer.image', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BREADCRUMBIMAGECONTAINER_BREADCRUMBIMAGE, _BREADCRUMBIMAGECONTAINER_MODELDBINFO, _BREADCRUMBIMAGECONTAINER_FACTORYBLOB, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=655,
)

_BREADCRUMBIMAGECONTAINER_BREADCRUMBIMAGE.fields_by_name['v10factory'].message_type = _BREADCRUMBIMAGECONTAINER_FACTORYBLOB
_BREADCRUMBIMAGECONTAINER_BREADCRUMBIMAGE.fields_by_name['modeldb'].message_type = _BREADCRUMBIMAGECONTAINER_MODELDBINFO
_BREADCRUMBIMAGECONTAINER_BREADCRUMBIMAGE.containing_type = _BREADCRUMBIMAGECONTAINER
_BREADCRUMBIMAGECONTAINER_MODELDBINFO.containing_type = _BREADCRUMBIMAGECONTAINER
_BREADCRUMBIMAGECONTAINER_FACTORYBLOB.containing_type = _BREADCRUMBIMAGECONTAINER
_BREADCRUMBIMAGECONTAINER.fields_by_name['image'].message_type = _BREADCRUMBIMAGECONTAINER_BREADCRUMBIMAGE
DESCRIPTOR.message_types_by_name['BreadCrumbImageContainer'] = _BREADCRUMBIMAGECONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BreadCrumbImageContainer = _reflection.GeneratedProtocolMessageType('BreadCrumbImageContainer', (_message.Message,), dict(

  BreadCrumbImage = _reflection.GeneratedProtocolMessageType('BreadCrumbImage', (_message.Message,), dict(
    DESCRIPTOR = _BREADCRUMBIMAGECONTAINER_BREADCRUMBIMAGE,
    __module__ = 'Image_pb2'
    # @@protoc_insertion_point(class_scope:rajant.bc.proto.BreadCrumbImageContainer.BreadCrumbImage)
    ))
  ,

  ModelDbInfo = _reflection.GeneratedProtocolMessageType('ModelDbInfo', (_message.Message,), dict(
    DESCRIPTOR = _BREADCRUMBIMAGECONTAINER_MODELDBINFO,
    __module__ = 'Image_pb2'
    # @@protoc_insertion_point(class_scope:rajant.bc.proto.BreadCrumbImageContainer.ModelDbInfo)
    ))
  ,

  FactoryBlob = _reflection.GeneratedProtocolMessageType('FactoryBlob', (_message.Message,), dict(
    DESCRIPTOR = _BREADCRUMBIMAGECONTAINER_FACTORYBLOB,
    __module__ = 'Image_pb2'
    # @@protoc_insertion_point(class_scope:rajant.bc.proto.BreadCrumbImageContainer.FactoryBlob)
    ))
  ,
  DESCRIPTOR = _BREADCRUMBIMAGECONTAINER,
  __module__ = 'Image_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.BreadCrumbImageContainer)
  ))
_sym_db.RegisterMessage(BreadCrumbImageContainer)
_sym_db.RegisterMessage(BreadCrumbImageContainer.BreadCrumbImage)
_sym_db.RegisterMessage(BreadCrumbImageContainer.ModelDbInfo)
_sym_db.RegisterMessage(BreadCrumbImageContainer.FactoryBlob)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
