# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Led.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Led.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\tLedProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\tLed.proto\"\x1f\n\x0bLEDSequence\x12\x10\n\x08sequence\x18\x01 \x01(\tB1\n\x17\x63om.rajant.bcapi.protosB\tLedProtosH\x02Z\t.;bcproto')
)




_LEDSEQUENCE = _descriptor.Descriptor(
  name='LEDSequence',
  full_name='LEDSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='LEDSequence.sequence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['LEDSequence'] = _LEDSEQUENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LEDSequence = _reflection.GeneratedProtocolMessageType('LEDSequence', (_message.Message,), dict(
  DESCRIPTOR = _LEDSEQUENCE,
  __module__ = 'Led_pb2'
  # @@protoc_insertion_point(class_scope:LEDSequence)
  ))
_sym_db.RegisterMessage(LEDSequence)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
