# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Log.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Log.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\tLogProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\tLog.proto\x1a\x0c\x43ommon.proto\"\x98\x01\n\x08\x42\x43Logger\x12\x1b\n\x04logs\x18\x01 \x03(\x0b\x32\r.BCLogger.Log\x1a=\n\x06LEDLog\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x65xtraMessage\x18\x03 \x01(\t\x1a\x30\n\x03Log\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x1a\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\n.BCRActionB1\n\x17\x63om.rajant.bcapi.protosB\tLogProtosH\x02Z\t.;bcproto')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_BCLOGGER_LEDLOG = _descriptor.Descriptor(
  name='LEDLog',
  full_name='BCLogger.LEDLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='BCLogger.LEDLog.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='BCLogger.LEDLog.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extraMessage', full_name='BCLogger.LEDLog.extraMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=130,
)

_BCLOGGER_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='BCLogger.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='BCLogger.Log.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='BCLogger.Log.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=180,
)

_BCLOGGER = _descriptor.Descriptor(
  name='BCLogger',
  full_name='BCLogger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logs', full_name='BCLogger.logs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BCLOGGER_LEDLOG, _BCLOGGER_LOG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=180,
)

_BCLOGGER_LEDLOG.containing_type = _BCLOGGER
_BCLOGGER_LOG.fields_by_name['action'].enum_type = Common__pb2._BCRACTION
_BCLOGGER_LOG.containing_type = _BCLOGGER
_BCLOGGER.fields_by_name['logs'].message_type = _BCLOGGER_LOG
DESCRIPTOR.message_types_by_name['BCLogger'] = _BCLOGGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BCLogger = _reflection.GeneratedProtocolMessageType('BCLogger', (_message.Message,), dict(

  LEDLog = _reflection.GeneratedProtocolMessageType('LEDLog', (_message.Message,), dict(
    DESCRIPTOR = _BCLOGGER_LEDLOG,
    __module__ = 'Log_pb2'
    # @@protoc_insertion_point(class_scope:BCLogger.LEDLog)
    ))
  ,

  Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), dict(
    DESCRIPTOR = _BCLOGGER_LOG,
    __module__ = 'Log_pb2'
    # @@protoc_insertion_point(class_scope:BCLogger.Log)
    ))
  ,
  DESCRIPTOR = _BCLOGGER,
  __module__ = 'Log_pb2'
  # @@protoc_insertion_point(class_scope:BCLogger)
  ))
_sym_db.RegisterMessage(BCLogger)
_sym_db.RegisterMessage(BCLogger.LEDLog)
_sym_db.RegisterMessage(BCLogger.Log)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
