# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Sam.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\tSamProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\tSam.proto\"\xa0\x01\n\x03Sam\x12\x1c\n\x05state\x18\x02 \x01(\x0e\x32\r.Sam.SamState\"{\n\x08SamState\x12\x1c\n\x18SAM_STATE_BEACON_DISABLE\x10\x00\x12\x1b\n\x17SAM_STATE_BEACON_ENABLE\x10\x01\x12\x19\n\x15SAM_STATE_BEACON_INIT\x10\x02\x12\x19\n\x15SAM_STATE_BEACON_STOP\x10\x03\x42\x31\n\x17\x63om.rajant.bcapi.protosB\tSamProtosH\x02Z\t.;bcproto')
)



_SAM_SAMSTATE = _descriptor.EnumDescriptor(
  name='SamState',
  full_name='Sam.SamState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SAM_STATE_BEACON_DISABLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_STATE_BEACON_ENABLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_STATE_BEACON_INIT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_STATE_BEACON_STOP', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=51,
  serialized_end=174,
)
_sym_db.RegisterEnumDescriptor(_SAM_SAMSTATE)


_SAM = _descriptor.Descriptor(
  name='Sam',
  full_name='Sam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='Sam.state', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAM_SAMSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=174,
)

_SAM.fields_by_name['state'].enum_type = _SAM_SAMSTATE
_SAM_SAMSTATE.containing_type = _SAM
DESCRIPTOR.message_types_by_name['Sam'] = _SAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sam = _reflection.GeneratedProtocolMessageType('Sam', (_message.Message,), dict(
  DESCRIPTOR = _SAM,
  __module__ = 'Sam_pb2'
  # @@protoc_insertion_point(class_scope:Sam)
  ))
_sym_db.RegisterMessage(Sam)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
