# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateMeta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StateMeta.proto',
  package='rajant.bc.proto',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\017StateMetaProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x0fStateMeta.proto\x12\x0frajant.bc.proto\"\xc2\x01\n\tStateMeta\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x37\n\treporting\x18\x02 \x01(\x0b\x32$.rajant.bc.proto.StateMeta.Reporting\x1an\n\tReporting\x12\x16\n\x07\x65xclude\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x1b\n\x0crateOfChange\x18\x02 \x01(\x08:\x05\x66\x61lse\x12,\n\x0etimestampField\x18\x03 \x01(\t:\x14statsTimestampMillis\"9\n\x0cStateMetaSet\x12)\n\x05\x66ield\x18\x01 \x03(\x0b\x32\x1a.rajant.bc.proto.StateMetaB7\n\x17\x63om.rajant.bcapi.protosB\x0fStateMetaProtosH\x02Z\t.;bcproto')
)




_STATEMETA_REPORTING = _descriptor.Descriptor(
  name='Reporting',
  full_name='rajant.bc.proto.StateMeta.Reporting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exclude', full_name='rajant.bc.proto.StateMeta.Reporting.exclude', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rateOfChange', full_name='rajant.bc.proto.StateMeta.Reporting.rateOfChange', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestampField', full_name='rajant.bc.proto.StateMeta.Reporting.timestampField', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("statsTimestampMillis").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=231,
)

_STATEMETA = _descriptor.Descriptor(
  name='StateMeta',
  full_name='rajant.bc.proto.StateMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='rajant.bc.proto.StateMeta.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reporting', full_name='rajant.bc.proto.StateMeta.reporting', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STATEMETA_REPORTING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=231,
)


_STATEMETASET = _descriptor.Descriptor(
  name='StateMetaSet',
  full_name='rajant.bc.proto.StateMetaSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='rajant.bc.proto.StateMetaSet.field', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=290,
)

_STATEMETA_REPORTING.containing_type = _STATEMETA
_STATEMETA.fields_by_name['reporting'].message_type = _STATEMETA_REPORTING
_STATEMETASET.fields_by_name['field'].message_type = _STATEMETA
DESCRIPTOR.message_types_by_name['StateMeta'] = _STATEMETA
DESCRIPTOR.message_types_by_name['StateMetaSet'] = _STATEMETASET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateMeta = _reflection.GeneratedProtocolMessageType('StateMeta', (_message.Message,), dict(

  Reporting = _reflection.GeneratedProtocolMessageType('Reporting', (_message.Message,), dict(
    DESCRIPTOR = _STATEMETA_REPORTING,
    __module__ = 'StateMeta_pb2'
    # @@protoc_insertion_point(class_scope:rajant.bc.proto.StateMeta.Reporting)
    ))
  ,
  DESCRIPTOR = _STATEMETA,
  __module__ = 'StateMeta_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.StateMeta)
  ))
_sym_db.RegisterMessage(StateMeta)
_sym_db.RegisterMessage(StateMeta.Reporting)

StateMetaSet = _reflection.GeneratedProtocolMessageType('StateMetaSet', (_message.Message,), dict(
  DESCRIPTOR = _STATEMETASET,
  __module__ = 'StateMeta_pb2'
  # @@protoc_insertion_point(class_scope:rajant.bc.proto.StateMetaSet)
  ))
_sym_db.RegisterMessage(StateMetaSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
