# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Sup.proto',
  package='sup',
  syntax='proto2',
  serialized_options=_b('\n\016com.rajant.supB\tSupProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\tSup.proto\x12\x03sup\"\xf1\x02\n\nSupMessage\x12&\n\x06header\x18\x01 \x02(\x0e\x32\x16.sup.SupMessage.Header\x12\x30\n\x0bmessageType\x18\x02 \x02(\x0e\x32\x1b.sup.SupMessage.MessageType\x12\x0f\n\x07service\x18\x03 \x02(\t\x12\x0b\n\x03qid\x18\x04 \x01(\t\x12\x0f\n\x07maxWait\x18\x05 \x01(\x05\x12\r\n\x05quiet\x18\x06 \x01(\x08\x12.\n\nproperties\x18\x07 \x03(\x0b\x32\x1a.sup.SupMessage.Properties\x12\x14\n\x0cotherAddress\x18\x08 \x01(\t\x12\x11\n\totherPort\x18\t \x01(\r\x1a(\n\nProperties\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\x1e\n\x06Header\x12\x14\n\x0cHEADER_VALUE\x10\x80\xe0\xd5\x9b\x07\"(\n\x0bMessageType\x12\x0b\n\x07REQUEST\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x42(\n\x0e\x63om.rajant.supB\tSupProtosH\x02Z\t.;bcproto')
)



_SUPMESSAGE_HEADER = _descriptor.EnumDescriptor(
  name='Header',
  full_name='sup.SupMessage.Header',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEADER_VALUE', index=0, number=1937076224,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=316,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_SUPMESSAGE_HEADER)

_SUPMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='sup.SupMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=348,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_SUPMESSAGE_MESSAGETYPE)


_SUPMESSAGE_PROPERTIES = _descriptor.Descriptor(
  name='Properties',
  full_name='sup.SupMessage.Properties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sup.SupMessage.Properties.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='sup.SupMessage.Properties.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=314,
)

_SUPMESSAGE = _descriptor.Descriptor(
  name='SupMessage',
  full_name='sup.SupMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='sup.SupMessage.header', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1937076224,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageType', full_name='sup.SupMessage.messageType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='sup.SupMessage.service', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qid', full_name='sup.SupMessage.qid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxWait', full_name='sup.SupMessage.maxWait', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quiet', full_name='sup.SupMessage.quiet', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='sup.SupMessage.properties', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otherAddress', full_name='sup.SupMessage.otherAddress', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otherPort', full_name='sup.SupMessage.otherPort', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SUPMESSAGE_PROPERTIES, ],
  enum_types=[
    _SUPMESSAGE_HEADER,
    _SUPMESSAGE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=388,
)

_SUPMESSAGE_PROPERTIES.containing_type = _SUPMESSAGE
_SUPMESSAGE.fields_by_name['header'].enum_type = _SUPMESSAGE_HEADER
_SUPMESSAGE.fields_by_name['messageType'].enum_type = _SUPMESSAGE_MESSAGETYPE
_SUPMESSAGE.fields_by_name['properties'].message_type = _SUPMESSAGE_PROPERTIES
_SUPMESSAGE_HEADER.containing_type = _SUPMESSAGE
_SUPMESSAGE_MESSAGETYPE.containing_type = _SUPMESSAGE
DESCRIPTOR.message_types_by_name['SupMessage'] = _SUPMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SupMessage = _reflection.GeneratedProtocolMessageType('SupMessage', (_message.Message,), dict(

  Properties = _reflection.GeneratedProtocolMessageType('Properties', (_message.Message,), dict(
    DESCRIPTOR = _SUPMESSAGE_PROPERTIES,
    __module__ = 'Sup_pb2'
    # @@protoc_insertion_point(class_scope:sup.SupMessage.Properties)
    ))
  ,
  DESCRIPTOR = _SUPMESSAGE,
  __module__ = 'Sup_pb2'
  # @@protoc_insertion_point(class_scope:sup.SupMessage)
  ))
_sym_db.RegisterMessage(SupMessage)
_sym_db.RegisterMessage(SupMessage.Properties)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
