# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: System.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Config_pb2 as Config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='System.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\014SystemProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x0cSystem.proto\x1a\x0c\x43onfig.proto\"\xca\x01\n\x13SystemConfiguration\x12\x1e\n\rconfiguration\x18\x01 \x01(\x0b\x32\x07.Config\x12\x14\n\x0cpublicSSLKey\x18\x02 \x01(\x0c\x12\x15\n\rprivateSSLKey\x18\x03 \x01(\x0c\x12-\n\x07sshKeys\x18\x04 \x01(\x0b\x32\x1c.SystemConfiguration.SshKeys\x1a\x37\n\x07SshKeys\x12\x12\n\nauthorized\x18\x01 \x01(\x0c\x12\x0b\n\x03\x64ss\x18\x02 \x01(\x0c\x12\x0b\n\x03rsa\x18\x03 \x01(\x0c\x42\x34\n\x17\x63om.rajant.bcapi.protosB\x0cSystemProtosH\x02Z\t.;bcproto')
  ,
  dependencies=[Config__pb2.DESCRIPTOR,])




_SYSTEMCONFIGURATION_SSHKEYS = _descriptor.Descriptor(
  name='SshKeys',
  full_name='SystemConfiguration.SshKeys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authorized', full_name='SystemConfiguration.SshKeys.authorized', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dss', full_name='SystemConfiguration.SshKeys.dss', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rsa', full_name='SystemConfiguration.SshKeys.rsa', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=233,
)

_SYSTEMCONFIGURATION = _descriptor.Descriptor(
  name='SystemConfiguration',
  full_name='SystemConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configuration', full_name='SystemConfiguration.configuration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publicSSLKey', full_name='SystemConfiguration.publicSSLKey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='privateSSLKey', full_name='SystemConfiguration.privateSSLKey', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sshKeys', full_name='SystemConfiguration.sshKeys', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SYSTEMCONFIGURATION_SSHKEYS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=233,
)

_SYSTEMCONFIGURATION_SSHKEYS.containing_type = _SYSTEMCONFIGURATION
_SYSTEMCONFIGURATION.fields_by_name['configuration'].message_type = Config__pb2._CONFIG
_SYSTEMCONFIGURATION.fields_by_name['sshKeys'].message_type = _SYSTEMCONFIGURATION_SSHKEYS
DESCRIPTOR.message_types_by_name['SystemConfiguration'] = _SYSTEMCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemConfiguration = _reflection.GeneratedProtocolMessageType('SystemConfiguration', (_message.Message,), dict(

  SshKeys = _reflection.GeneratedProtocolMessageType('SshKeys', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMCONFIGURATION_SSHKEYS,
    __module__ = 'System_pb2'
    # @@protoc_insertion_point(class_scope:SystemConfiguration.SshKeys)
    ))
  ,
  DESCRIPTOR = _SYSTEMCONFIGURATION,
  __module__ = 'System_pb2'
  # @@protoc_insertion_point(class_scope:SystemConfiguration)
  ))
_sym_db.RegisterMessage(SystemConfiguration)
_sym_db.RegisterMessage(SystemConfiguration.SshKeys)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
