# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Troip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Troip.proto',
  package='Troip',
  syntax='proto2',
  serialized_options=_b('\n\027com.rajant.bcapi.protosB\013TroipProtosH\002Z\t.;bcproto'),
  serialized_pb=_b('\n\x0bTroip.proto\x12\x05Troip\"\xd0\x06\n\x08TroipMsg\x12/\n\x08magicNum\x18\x01 \x02(\x0e\x32\x1d.Troip.TroipMsg.TroipMagicNum\x12-\n\x07msgType\x18\x02 \x02(\x0e\x32\x1c.Troip.TroipMsg.TroipMsgType\x12\x0e\n\x06seqNum\x18\x05 \x01(\r\x12\r\n\x05index\x18\x06 \x01(\r\x12/\n\x08\x62\x63\x61piVer\x18\x07 \x01(\x0e\x32\x1d.Troip.TroipMsg.TroipMinBcapi\x12\x11\n\tserialNum\x18\x08 \x01(\t\x12\x0c\n\x04name\x18\t \x01(\t\x12\x32\n\x08\x65lection\x18\x03 \x01(\x0b\x32 .Troip.TroipMsg.TroipElectionBid\x12,\n\tsignOnOff\x18\x04 \x01(\x0b\x32\x19.Troip.TroipMsg.TroipSign\x1aQ\n\x13TroipElectionRating\x12\x0e\n\x06rating\x18\x01 \x01(\r\x12\x0e\n\x06ipaddr\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x0c\n\x04\x62ias\x18\x04 \x01(\x05\x1a\x85\x01\n\x10TroipElectionBid\x12\x36\n\tbidRating\x18\x01 \x01(\x0b\x32#.Troip.TroipMsg.TroipElectionRating\x12\x11\n\tbidMcaddr\x18\x02 \x01(\t\x12\x12\n\nbidMixAddr\x18\x03 \x01(\t\x12\x12\n\nbidMixPort\x18\x04 \x01(\r\x1a\x33\n\tTroipSign\x12\x12\n\nsignIpaddr\x18\x01 \x01(\t\x12\x12\n\nsignMcaddr\x18\x02 \x01(\t\".\n\rTroipMagicNum\x12\x1d\n\x15MIXMASTER_MAGIC_VALUE\x10\x80\xf0\xa5\xeb\x06\",\n\rTroipMinBcapi\x12\x1b\n\x17MIXMASTER_MINIMUM_BCAPI\x10\x02\"\xa2\x01\n\x0cTroipMsgType\x12\x1b\n\x17TROIP_MSG_TYPE_ELECTION\x10\x00\x12\x1b\n\x17TROIP_MSG_TYPE_SIGN_OFF\x10\x01\x12\x1a\n\x16TROIP_MSG_TYPE_SIGN_ON\x10\x02\x12\x1d\n\x19TROIP_MSG_TYPE_CRASH_CTRL\x10\x03\x12\x1d\n\x19TROIP_MSG_TYPE_CRASH_VOIP\x10\x04\x42\x33\n\x17\x63om.rajant.bcapi.protosB\x0bTroipProtosH\x02Z\t.;bcproto')
)



_TROIPMSG_TROIPMAGICNUM = _descriptor.EnumDescriptor(
  name='TroipMagicNum',
  full_name='Troip.TroipMsg.TroipMagicNum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MIXMASTER_MAGIC_VALUE', index=0, number=1835628544,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=614,
  serialized_end=660,
)
_sym_db.RegisterEnumDescriptor(_TROIPMSG_TROIPMAGICNUM)

_TROIPMSG_TROIPMINBCAPI = _descriptor.EnumDescriptor(
  name='TroipMinBcapi',
  full_name='Troip.TroipMsg.TroipMinBcapi',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MIXMASTER_MINIMUM_BCAPI', index=0, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=662,
  serialized_end=706,
)
_sym_db.RegisterEnumDescriptor(_TROIPMSG_TROIPMINBCAPI)

_TROIPMSG_TROIPMSGTYPE = _descriptor.EnumDescriptor(
  name='TroipMsgType',
  full_name='Troip.TroipMsg.TroipMsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TROIP_MSG_TYPE_ELECTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TROIP_MSG_TYPE_SIGN_OFF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TROIP_MSG_TYPE_SIGN_ON', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TROIP_MSG_TYPE_CRASH_CTRL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TROIP_MSG_TYPE_CRASH_VOIP', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=709,
  serialized_end=871,
)
_sym_db.RegisterEnumDescriptor(_TROIPMSG_TROIPMSGTYPE)


_TROIPMSG_TROIPELECTIONRATING = _descriptor.Descriptor(
  name='TroipElectionRating',
  full_name='Troip.TroipMsg.TroipElectionRating',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rating', full_name='Troip.TroipMsg.TroipElectionRating.rating', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipaddr', full_name='Troip.TroipMsg.TroipElectionRating.ipaddr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Troip.TroipMsg.TroipElectionRating.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bias', full_name='Troip.TroipMsg.TroipElectionRating.bias', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=423,
)

_TROIPMSG_TROIPELECTIONBID = _descriptor.Descriptor(
  name='TroipElectionBid',
  full_name='Troip.TroipMsg.TroipElectionBid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bidRating', full_name='Troip.TroipMsg.TroipElectionBid.bidRating', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bidMcaddr', full_name='Troip.TroipMsg.TroipElectionBid.bidMcaddr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bidMixAddr', full_name='Troip.TroipMsg.TroipElectionBid.bidMixAddr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bidMixPort', full_name='Troip.TroipMsg.TroipElectionBid.bidMixPort', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=559,
)

_TROIPMSG_TROIPSIGN = _descriptor.Descriptor(
  name='TroipSign',
  full_name='Troip.TroipMsg.TroipSign',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signIpaddr', full_name='Troip.TroipMsg.TroipSign.signIpaddr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signMcaddr', full_name='Troip.TroipMsg.TroipSign.signMcaddr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=612,
)

_TROIPMSG = _descriptor.Descriptor(
  name='TroipMsg',
  full_name='Troip.TroipMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='magicNum', full_name='Troip.TroipMsg.magicNum', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1835628544,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='Troip.TroipMsg.msgType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqNum', full_name='Troip.TroipMsg.seqNum', index=2,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='Troip.TroipMsg.index', index=3,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bcapiVer', full_name='Troip.TroipMsg.bcapiVer', index=4,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialNum', full_name='Troip.TroipMsg.serialNum', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Troip.TroipMsg.name', index=6,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='election', full_name='Troip.TroipMsg.election', index=7,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signOnOff', full_name='Troip.TroipMsg.signOnOff', index=8,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TROIPMSG_TROIPELECTIONRATING, _TROIPMSG_TROIPELECTIONBID, _TROIPMSG_TROIPSIGN, ],
  enum_types=[
    _TROIPMSG_TROIPMAGICNUM,
    _TROIPMSG_TROIPMINBCAPI,
    _TROIPMSG_TROIPMSGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=871,
)

_TROIPMSG_TROIPELECTIONRATING.containing_type = _TROIPMSG
_TROIPMSG_TROIPELECTIONBID.fields_by_name['bidRating'].message_type = _TROIPMSG_TROIPELECTIONRATING
_TROIPMSG_TROIPELECTIONBID.containing_type = _TROIPMSG
_TROIPMSG_TROIPSIGN.containing_type = _TROIPMSG
_TROIPMSG.fields_by_name['magicNum'].enum_type = _TROIPMSG_TROIPMAGICNUM
_TROIPMSG.fields_by_name['msgType'].enum_type = _TROIPMSG_TROIPMSGTYPE
_TROIPMSG.fields_by_name['bcapiVer'].enum_type = _TROIPMSG_TROIPMINBCAPI
_TROIPMSG.fields_by_name['election'].message_type = _TROIPMSG_TROIPELECTIONBID
_TROIPMSG.fields_by_name['signOnOff'].message_type = _TROIPMSG_TROIPSIGN
_TROIPMSG_TROIPMAGICNUM.containing_type = _TROIPMSG
_TROIPMSG_TROIPMINBCAPI.containing_type = _TROIPMSG
_TROIPMSG_TROIPMSGTYPE.containing_type = _TROIPMSG
DESCRIPTOR.message_types_by_name['TroipMsg'] = _TROIPMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TroipMsg = _reflection.GeneratedProtocolMessageType('TroipMsg', (_message.Message,), dict(

  TroipElectionRating = _reflection.GeneratedProtocolMessageType('TroipElectionRating', (_message.Message,), dict(
    DESCRIPTOR = _TROIPMSG_TROIPELECTIONRATING,
    __module__ = 'Troip_pb2'
    # @@protoc_insertion_point(class_scope:Troip.TroipMsg.TroipElectionRating)
    ))
  ,

  TroipElectionBid = _reflection.GeneratedProtocolMessageType('TroipElectionBid', (_message.Message,), dict(
    DESCRIPTOR = _TROIPMSG_TROIPELECTIONBID,
    __module__ = 'Troip_pb2'
    # @@protoc_insertion_point(class_scope:Troip.TroipMsg.TroipElectionBid)
    ))
  ,

  TroipSign = _reflection.GeneratedProtocolMessageType('TroipSign', (_message.Message,), dict(
    DESCRIPTOR = _TROIPMSG_TROIPSIGN,
    __module__ = 'Troip_pb2'
    # @@protoc_insertion_point(class_scope:Troip.TroipMsg.TroipSign)
    ))
  ,
  DESCRIPTOR = _TROIPMSG,
  __module__ = 'Troip_pb2'
  # @@protoc_insertion_point(class_scope:Troip.TroipMsg)
  ))
_sym_db.RegisterMessage(TroipMsg)
_sym_db.RegisterMessage(TroipMsg.TroipElectionRating)
_sym_db.RegisterMessage(TroipMsg.TroipElectionBid)
_sym_db.RegisterMessage(TroipMsg.TroipSign)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
