inventario_pmp_url : /inventario/get/tipo/PMP/
cambium_data_ip_url_base : /cambium_data/get_ip/
predicciones_list_add: /predicciones/add_list/
db_api_url: http://192.168.2.223:8001/

RX:
  neuralprophet_parameters:
    n_forecasts: 3
    growth: "off"
    yearly_seasonality: false
    weekly_seasonality: false
    daily_seasonality: false
    n_lags: 5
    #num_hidden_layers: 1  # Valor por defecto
    #d_hidden: 64  # Valor por defecto
    learning_rate: 0.002
    #optimizer: "AdamW"  # Valor por defecto
    #ar_reg: 0.0  # Valor por defecto
    normalize: "minmax"
    epochs: 180
    #drop_missing: false  # Valor por defecto
SNR_V:
  neuralprophet_parameters:
    n_forecasts: 3
    growth: "off"
    yearly_seasonality: false
    weekly_seasonality: false
    daily_seasonality: false
    n_lags: 5
    #num_hidden_layers: 1  # Valor por defecto
    #d_hidden: 64  # Valor por defecto
    learning_rate: 0.002
    #optimizer: "AdamW"  # Valor por defecto
    #ar_reg: 0.0  # Valor por defecto
    normalize: "minmax"
    epochs: 180
    #drop_missing: false  # Valor por defecto
SNR_H:
  neuralprophet_parameters:
    n_forecasts: 3
    growth: "off"
    yearly_seasonality: false
    weekly_seasonality: false
    daily_seasonality: false
    n_lags: 5
    #num_hidden_layers: 1  # Valor por defecto
    #d_hidden: 64  # Valor por defecto
    learning_rate: 0.002
    #optimizer: "AdamW"  # Valor por defecto
    #ar_reg: 0.0  # Valor por defecto
    normalize: "minmax"
    epochs: 180
    #drop_missing: false  # Valor por defecto
AirRx:
  neuralprophet_parameters:
    n_forecasts: 3
    growth: "off"
    yearly_seasonality: false
    weekly_seasonality: false
    daily_seasonality: false
    n_lags: 5
    #num_hidden_layers: 1  # Valor por defecto
    #d_hidden: 64  # Valor por defecto
    learning_rate: 0.002
    #optimizer: "AdamW"  # Valor por defecto
    #ar_reg: 0.0  # Valor por defecto
    normalize: "minmax"
    epochs: 180
    #drop_missing: false  # Valor por defecto