# routes/routes.py
def init_routes(app):
    app.include_router(router)
    app.include_router(usuarios_router, prefix="/usuarios", tags=["Usuarios"])
    app.include_router(eventos_router, prefix="/eventos", tags=["Eventos"])
    app.include_router(inventario_router, prefix="/inventario", tags=["Inventario"])    
    app.include_router(roles_router, prefix="/roles", tags=["Roles"])
    app.include_router(marcas_router, prefix="/marcas", tags=["Marcas"])
    app.include_router(sensores_router, prefix="/sensores", tags=["Sensores"])
    app.include_router(tipos_router, prefix="/tipos", tags=["Tipos"])
    app.include_router(estructura_red_router, prefix="/estructura", tags=["Estructura de red"])
    app.include_router(ubicacion_gps_router, prefix="/ubicacion_gps", tags=["Ubicación GPS"])
    app.include_router(snmp_conf_router, prefix="/snmp_conf", tags=["Configuración SNMP"])
    app.include_router(rajant_data_router, prefix="/rajant_data", tags=["Datos Rajant"])
    app.include_router(latencia_router, prefix="/latencia", tags=["Latencia"])
    app.include_router(cambium_data, prefix="/cambium_data", tags=["Datos Cambium"])
    app.include_router(instamesh_router, prefix="/instamesh", tags=["Instamesh"])
    app.include_router(wired_router, prefix="/wired", tags=["Wired"])
    app.include_router(wireless_router, prefix="/wireless", tags=["Wireless"])
    app.include_router(clustering_data_router, prefix="/clustering", tags=["Clustering"])
    # app.include_router(LTE_data_router, prefix="/LTE_data", tags=["Datos LTE"])
    # app.include_router(websocket_lte_router, prefix="/wsl", tags=["Websockets LTE"])
    app.include_router(predicciones_router, prefix="/predicciones", tags=["Predicciones"])
    app.include_router(mantenimientodb_router, prefix="/mantenimientodb", tags=["Mantenimiento DB"])
    app.include_router(api_info_router, prefix="/api", tags=["Monitoreo"])
