api:
  eventos:
    add_list: /eventos/add_list
    add: /eventos/add
    get: /eventos/get
    get_ip: /eventos/get_ip
    urgentes: /eventos/urgentes

  latencia:
    get_poor_latency: /latencia/get_poor_latency

  cambium_data:
    get: /cambium_data/get

whatsapp:
  twilio:
    account_sid: 'TU_TWILIO_ACCOUNT_SID_AQUI'
    auth_token: 'TU_TWILIO_AUTH_TOKEN_AQUI'
    whatsapp_number: 'whatsapp:TU_NUMERO_DE_TWILIO'
    my_whatsapp_number: 'whatsapp:TU_NUMERO_PERSONAL'

  mudslice:
    id_collahuasi: ["+56977566595", "120363027104819888@g.us", "+56971083001", "+56982280571", "+56976426949", "+56939496396"]
    #id_collahuasi: ["+56977566595"]
    #id_default: ["+56977566595"]

email:
  smtp_server: 'smtp.TU_SERVIDOR_SMTP.com'
  smtp_port: 587
  sender_email: 'TU_EMAIL_AQUI'
  sender_password: 'TU_PASSWORD_O_TOKEN_AQUI'
  recipients: ['EMAIL1_AQUI', 'EMAIL2_AQUI']

telegram:
  token: 'TU_TELEGRAM_BOT_TOKEN_AQUI'
  chat_id: 'TU_CHAT_ID_AQUI'

